# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               SOIITAIRE
tagline:             '写代码的小别'
description:         '创业中的小别，互联网相关。'
url:                 http://soiitaire.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              soiitaire
  twitter:           https://twitter.com/soiitaire
  weibo:             http://weibo.com/soiitaire
  douban:            http://www.douban.com/people/soiitaire/
  github:            https://github.com/soiitaire
  instagram:         http://instagram.com/soiitaire

# Custom vars
version:             1.0.0
